version: '3'
services:
  config:
    image: config
    ports:
      - 8081:8081
  discovery:
    image: discovery
    ports:
      - 8761:8761
    depends_on:
      - config
  user-service:
    image: user-service
    depends_on:
      - discovery
      - config











