version: '3'
services:
  discover-service:
    image: discover-service
    container_name: discover-container
    ports:
      - 8761:8761
  config-service:
    image: config-service
    container_name: config-container
    ports:
      - 8081:8081
    depends_on:
      - discover-service
    links:
      - discover-service



  user-service:
    image: user-service
    container_name: user-service-container
    restart: always
    links:
      - discover-service
      - config-service
    depends_on:
      - discover-service
      - config-service
















