version: '3'
services:
  config:
    image: config
    ports:
      - 8081:8081
    networks:
      fortlom:
  discovery:
    image: discovery
    ports:
      - 8761:8761
    depends_on:
      - config
    networks:
      fortlom:
networks:
  fortlom:












