version: '3'
services:



  gateway-service:
    image: public.ecr.aws/j3l9t1g6/gateway-service
    ports:
      - 8080:8080
    depends_on:

      - discover-service
    links:

      - discover-service
    environment:
      - eureka.client.service-url.defaultZone=http://discover-service:8761/eureka/
  user-service:
    image: public.ecr.aws/j3l9t1g6/user-service
    depends_on:

      - discover-service
      - gateway-service
    links:

      - discover-service
      - gateway-service
    environment:
      - eureka.client.service-url.defaultZone=http://discover-service:8761/eureka/
  support-service:
    image: public.ecr.aws/j3l9t1g6/support-service
    depends_on:

      - discover-service
      - gateway-service
    links:

      - discover-service
      - gateway-service
    environment:
      - eureka.client.service-url.defaultZone=http://discover-service:8761/eureka/
  publication-service:
    image: public.ecr.aws/j3l9t1g6/publication-service
    depends_on:

      - discover-service
      - gateway-service
    links:

      - discover-service
      - gateway-service
    environment:
      - eureka.client.service-url.defaultZone=http://discover-service:8761/eureka/
  forum-service:
    image: public.ecr.aws/j3l9t1g6/forum-service
    depends_on:

      - discover-service
      - gateway-service
    links:

      - discover-service
      - gateway-service
    environment:
      - eureka.client.service-url.defaultZone=http://discover-service:8761/eureka/
  comment-service:
    image: public.ecr.aws/j3l9t1g6/comment-service
    depends_on:

      - discover-service
      - gateway-service
    links:
      - config-service
      - discover-service
      - gateway-service
    environment:
      - eureka.client.service-url.defaultZone=http://discover-service:8761/eureka/
  report-service:
    image: public.ecr.aws/j3l9t1g6/report-service
    depends_on:

      - discover-service
      - gateway-service
    links:

      - discover-service
      - gateway-service
    environment:
      - eureka.client.service-url.defaultZone=http://discover-service:8761/eureka/





















