server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://54.147.168.82:8761/eureka
  instance:
    hostname: gateway-service
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/v1/reportservice/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/commentservice/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/userservice/**
        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/api/v1/contentservice/**
        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/v1/supportservice/**
        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/api/v1/**
