server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/api/v1/**
        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/api/v1/publications/**, /api/v1/multimedias/**, /api/v1/events/**
        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/v1/rates/**, /api/v1/follows/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/**, /api/v1/forumcomments/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/artists/**, /api/v1/fanatics/**