server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: feature/gateway-service
          uri: https://github.com/giusencito/fortlom-microservices
          search-paths: config-data

  application:
    name: config-service



